name: stagexl_richtextfield
version: 0.1.3
author: Alex Gann <k.alexgann@gmail.com>
description: StageXL Extension for RichTextField support.
homepage: https://github.com/realbluesky/StageXL_RichTextField
documentation: https://github.com/realbluesky/StageXL_RichTextField
dependencies:
  browser: '>=0.10.0 <0.11.0'
  stagexl: '>=0.13.0 <0.14.0'
