name: stagexl_richtextfield
version: 0.1.2
author: Alex Gann <k.alexgann@gmail.com>
description: StageXL Extension for RichTextField support.
homepage: https://github.com/realbluesky/StageXL_RichTextField
documentation: https://github.com/realbluesky/StageXL_RichTextField
dependencies:
  browser: '>=0.9.0 <0.11.0'
  stagexl: '>=0.9.0 <0.11.0'
