name: stagexl_richtextfield
version: 0.1.5
authors:
- Alex Gann <k.alexgann@gmail.com>
- Bernhard Pichler <support@stagexl.org>
author:
description: StageXL Extension for RichTextField support.
homepage: https://github.com/bp74/StageXL_RichTextField
documentation: https://github.com/bp74/StageXL_RichTextField

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  browser: any
  stagexl: '^1.0.0'

transformers:
- $dart2js:
    commandLineOptions: ["--trust-type-annotations", "--trust-primitives", "--dump-info"]
    minify: true
