name: stagexl_richtextfield
version: 0.3.0
authors:
- Alex Gann <k.alexgann@gmail.com>
- Bernhard Pichler <support@stagexl.org>
author:
description: StageXL Extension for RichTextField support.
homepage: https://github.com/bp74/StageXL_RichTextField
documentation: https://github.com/bp74/StageXL_RichTextField

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  stagexl: '>=1.4.0 <2.0.0'

dev_dependencies:
  build_test: ^0.10.3+1
  build_runner: ^0.10.1
  build_web_compilers: ^0.4.2+1
