name: stagexl_richtextfield
version: 0.1.0
author: Alex Gann <k.alexgann@gmail.com>
description: StageXL Extension for RichTextField support.
homepage: https://github.com/realbluesky/StageXL_RichTextField
documentation: https://github.com/realbluesky/StageXL_RichTextField
dependencies:
  browser: '>=0.9.0 <0.10.0'
  stagexl: '>=0.8.8 <0.9.0'
  xml: '>=0.9.4 <0.10.0'
