name: stagexl_richtextfield
version: 0.3.0-dev
authors:
- Alex Gann <k.alexgann@gmail.com>
- Bernhard Pichler <support@stagexl.org>
author:
description: StageXL Extension for RichTextField support.
homepage: https://github.com/bp74/StageXL_RichTextField
documentation: https://github.com/bp74/StageXL_RichTextField

environment:
  sdk: '>=2.0.0-dev.36 <2.0.0'

dependencies:
  stagexl:
    version: '>=1.3.2-dev <2.0.0'
    git: https://github.com/bp74/StageXL

dev_dependencies:
  build_runner: ^0.8.9
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0+3
